apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook
webhooks:
  - name: mutate.default.svc
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions: ["v1"]
    objectSelector:
      matchLabels:
        app: sdp
    rules:
      - apiGroups: ["apps", ""]
        resources:          
          - "persistentvolumeclaims"
        apiVersions:
          - "*"
        operations:
          - CREATE
        scope: "Namespaced"
    clientConfig:
      service:
        name: mutate
        namespace: default
        path: /mutate/
      caBundle: <caBundle>
